решение задач
dmk7eshko/js-learning pull request #1
Opened 2024-08-26 22:44 UTC by dmk7eshko

2024-08-27 21:22 UTC, DimaLom requested changes

2024-08-27 21:22 UTC, DimaLom commented on tasks/checkNumber.js
> +    const inputNumber = prompt('input ur number', yourNumber);
promt сдесь не нужен, так же как и переменная yourNumber. Вообще непонятно зачем ты ее завел)

2024-08-27 21:22 UTC, DimaLom commented on tasks/checkNumber.js
> +    return num
в условии задачи стоит вернуть строку, ты выводишь что-то в консоль и алерт. А возвращаешь принимаемое функцией число. Задача решена не верно

2024-08-27 21:22 UTC, DimaLom commented on tasks/humanDescription.js
> +
В целом задача решена верно. Добавь решение с использованием стрелочной функции

2024-08-27 21:23 UTC, dmk7eshko commented on tasks/checkNumber.js
> +    const inputNumber = prompt('input ur number', yourNumber);
думал так удобнее будет) немного наворотил, могу строго по условию задачи переделать

2024-08-30 16:16 UTC, DimaLom approved these changes

2024-08-30 19:09 UTC, merged